-- MekyyStudio V23
-- Auth/email-flow support + privilege hardening.
-- Run after schema-v22.sql.

-- SECURITY: SECURITY DEFINER helpers must never be callable by anonymous users.
revoke execute on function public.admin_clear_project_chat(bigint) from public;
revoke execute on function public.admin_delete_project(bigint) from public;
revoke execute on function public.admin_delete_storage_file(text,text) from public;
revoke execute on function public.admin_delete_user(uuid) from public;
revoke execute on function public.admin_empty_storage_bucket(text) from public;
revoke execute on function public.admin_list_profiles() from public;
revoke execute on function public.admin_reset_chat() from public;
revoke execute on function public.admin_reset_delivery() from public;
revoke execute on function public.admin_reset_orders() from public;
revoke execute on function public.admin_reset_payments() from public;
revoke execute on function public.admin_reset_refunds() from public;
revoke execute on function public.admin_send_message(bigint,text,text,text,text,bigint) from public;
revoke execute on function public.admin_update_profile(uuid,text,text) from public;
revoke execute on function public.cancel_my_project(bigint) from public;
revoke execute on function public.delete_my_account() from public;
revoke execute on function public.handle_new_user() from public;
revoke execute on function public.is_admin() from public;
revoke execute on function public.is_worker() from public;
revoke execute on function public.my_profile_role() from public;
revoke execute on function public.notify_project_change() from public;
revoke execute on function public.request_project_refund(bigint) from public;
revoke execute on function public.submit_project_payment(bigint,text) from public;
revoke execute on function public.upsert_worker_note(bigint,text) from public;
revoke execute on function public.worker_send_message(bigint,text,text,text,text,bigint) from public;

grant execute on function public.admin_clear_project_chat(bigint) to authenticated;
grant execute on function public.admin_delete_project(bigint) to authenticated;
grant execute on function public.admin_delete_storage_file(text,text) to authenticated;
grant execute on function public.admin_delete_user(uuid) to authenticated;
grant execute on function public.admin_empty_storage_bucket(text) to authenticated;
grant execute on function public.admin_list_profiles() to authenticated;
grant execute on function public.admin_reset_chat() to authenticated;
grant execute on function public.admin_reset_delivery() to authenticated;
grant execute on function public.admin_reset_orders() to authenticated;
grant execute on function public.admin_reset_payments() to authenticated;
grant execute on function public.admin_reset_refunds() to authenticated;
grant execute on function public.admin_send_message(bigint,text,text,text,text,bigint) to authenticated;
grant execute on function public.admin_update_profile(uuid,text,text) to authenticated;
grant execute on function public.cancel_my_project(bigint) to authenticated;
grant execute on function public.delete_my_account() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_worker() to authenticated;
grant execute on function public.my_profile_role() to authenticated;
grant execute on function public.request_project_refund(bigint) to authenticated;
grant execute on function public.submit_project_payment(bigint,text) to authenticated;
grant execute on function public.upsert_worker_note(bigint,text) to authenticated;
grant execute on function public.worker_send_message(bigint,text,text,text,text,bigint) to authenticated;

-- Small audit table for email/auth events generated by the frontend.
create table if not exists public.auth_email_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  email text,
  event_type text not null,
  created_at timestamptz not null default now()
);

alter table public.auth_email_events enable row level security;
drop policy if exists "users can view own auth email events" on public.auth_email_events;
create policy "users can view own auth email events"
on public.auth_email_events for select to authenticated
using (user_id = auth.uid());

drop policy if exists "users can insert own auth email events" on public.auth_email_events;
create policy "users can insert own auth email events"
on public.auth_email_events for insert to authenticated
with check (user_id = auth.uid());
