-- Run this in Supabase > SQL Editor.
-- This is the simple database foundation.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  role text default 'customer',
  created_at timestamptz default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  product text not null,
  title text,
  description text,
  status text default 'new',
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete cascade,
  message text not null,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.messages enable row level security;

create policy "users can view own profile"
on public.profiles for select to authenticated
using (auth.uid() = id);

create policy "users can view own projects"
on public.projects for select to authenticated
using (auth.uid() = user_id);

create policy "users can create own projects"
on public.projects for insert to authenticated
with check (auth.uid() = user_id);

create policy "users can view own messages"
on public.messages for select to authenticated
using (
  exists (
    select 1 from public.projects
    where projects.id = messages.project_id
    and projects.user_id = auth.uid()
  )
);

create policy "users can send own messages"
on public.messages for insert to authenticated
with check (auth.uid() = sender_id);

-- Automatically create a profile after registration.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, email)
  values (new.id, new.raw_user_meta_data->>'name', new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- After you create your own account, we can set your profile role to admin.
-- Example:
-- update public.profiles set role='admin' where email='YOUR_EMAIL_HERE';