-- MekyyStudio V21
-- Run AFTER schema-v20.sql.
-- Fixes admin profile saving, worker notes, in-page notifications,
-- realtime payment updates, and safe delivery visibility.

alter table public.projects drop column if exists worker_note;

create table if not exists public.worker_notes (
  project_id bigint primary key references public.projects(id) on delete cascade,
  note text not null default '',
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);
alter table public.worker_notes enable row level security;
drop policy if exists "admin can manage worker notes" on public.worker_notes;
create policy "admin can manage worker notes" on public.worker_notes for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "assigned worker can manage worker notes" on public.worker_notes;
create policy "assigned worker can manage worker notes" on public.worker_notes for all to authenticated using (public.is_worker() and exists(select 1 from public.projects pr where pr.id=worker_notes.project_id and pr.assigned_worker_id=auth.uid())) with check (public.is_worker() and exists(select 1 from public.projects pr where pr.id=worker_notes.project_id and pr.assigned_worker_id=auth.uid()));

-- ------------------------------------------------------------
-- NOTIFICATIONS
-- ------------------------------------------------------------
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  project_id bigint references public.projects(id) on delete cascade,
  type text not null default 'info',
  title text not null,
  body text,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.notifications enable row level security;
drop policy if exists "users can view own notifications" on public.notifications;
create policy "users can view own notifications"
on public.notifications for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "users can mark own notifications read" on public.notifications;
create policy "users can mark own notifications read"
on public.notifications for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- ------------------------------------------------------------
-- ADMIN PROFILE UPDATE RPC
-- Avoids browser-side RLS/profile update failures when changing
-- worker/customer names or roles.
-- ------------------------------------------------------------
create or replace function public.admin_update_profile(
  p_user_id uuid,
  p_name text,
  p_role text
)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare r public.profiles;
begin
  if not public.is_admin() then raise exception 'Admin only'; end if;
  if p_role not in ('customer','worker','admin') then raise exception 'Invalid role'; end if;
  if p_user_id = auth.uid() and p_role <> 'admin' then raise exception 'You cannot remove your own admin role'; end if;
  update public.profiles
  set name = nullif(trim(p_name), ''), role = p_role
  where id = p_user_id
  returning * into r;
  if r.id is null then raise exception 'Profile not found'; end if;
  return r;
end;
$$;
revoke all on function public.admin_update_profile(uuid,text,text) from public;
grant execute on function public.admin_update_profile(uuid,text,text) to authenticated;

-- ------------------------------------------------------------
-- NOTIFICATION TRIGGER
-- ------------------------------------------------------------
create or replace function public.notify_project_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare admin_id uuid;
begin
  if TG_OP = 'UPDATE' then
    if old.payment_status is distinct from new.payment_status and new.payment_status = 'submitted' then
      for admin_id in select id from public.profiles where role='admin' loop
        insert into public.notifications(user_id,project_id,type,title,body)
        values(admin_id,new.id,'payment','Payment submitted',coalesce(new.product,'Order')||' has been marked as paid by the customer and is waiting for confirmation.');
      end loop;
    end if;

    if old.payment_status is distinct from new.payment_status and new.payment_status = 'confirmed' then
      insert into public.notifications(user_id,project_id,type,title,body)
      values(new.user_id,new.id,'success','Payment confirmed','Your payment has been confirmed. Your receipt and final download are now available.');
      for admin_id in select id from public.profiles where role='admin' loop
        insert into public.notifications(user_id,project_id,type,title,body)
        values(admin_id,new.id,'success','Payment received',coalesce(new.product,'Order')||' payment is confirmed.');
      end loop;
    end if;

    if old.status is distinct from new.status and new.status = 'awaiting_payment' then
      insert into public.notifications(user_id,project_id,type,title,body)
      values(new.user_id,new.id,'info','Product ready','Your product is ready. Complete payment to unlock the final download.');
    end if;

    if old.assigned_worker_id is distinct from new.assigned_worker_id and new.assigned_worker_id is not null then
      insert into public.notifications(user_id,project_id,type,title,body)
      values(new.assigned_worker_id,new.id,'assignment','New assigned order','You have been assigned to '||coalesce(new.product,'a customer order')||'.');
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_project_notifications on public.projects;
create trigger trg_project_notifications
after update on public.projects
for each row execute procedure public.notify_project_change();

-- ------------------------------------------------------------
-- REALTIME
-- ------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then
    execute 'alter publication supabase_realtime add table public.notifications';
  end if;
end $$;

-- Make sure project/message realtime remains enabled.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='projects') then
    execute 'alter publication supabase_realtime add table public.projects';
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='messages') then
    execute 'alter publication supabase_realtime add table public.messages';
  end if;
end $$;

-- ------------------------------------------------------------
-- DELIVERY ACCESS
-- The file may be stored before payment, but the customer is not
-- allowed to read it until payment is confirmed. Admin/worker can read.
-- ------------------------------------------------------------
drop policy if exists "delivery files read allowed" on storage.objects;
create policy "delivery files read allowed"
on storage.objects for select to authenticated
using (
  bucket_id='deliveries'
  and (
    public.is_admin()
    or public.is_worker()
    or exists(
      select 1 from public.projects pr
      where pr.user_id=auth.uid()
        and pr.delivery_path=storage.objects.name
        and pr.payment_status='confirmed'
    )
  )
);
